# Finished!

In [2]:
from numpy.random import rand
from numpy import transpose
import numpy as np
from time import time

In [3]:
rand(2,3)

array([[ 0.02120914,  0.59299567,  0.48529874],
       [ 0.19291083,  0.88036179,  0.4108865 ]])

In [8]:
def gen_random(Params):
    """generate a numpy binary matrix where row i is IID binary 
    with probability P[i] and has length n"""
    P,n=Params
    m=P.shape[0]
    R=rand(m,n)
    B=1*(R<P)
    return B

In [9]:
n=10
P=np.array([np.arange(0.4,0.61,0.1),]).transpose()
print P
B=gen_random((P,n))


[[ 0.4]
 [ 0.5]
 [ 0.6]]


In [10]:
B

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1, 1, 1, 0, 1],
       [0, 0, 1, 0, 0, 0, 1, 1, 1, 1]])

In [11]:
# define the P[i]'s to in the range from 0.4 to 0.6
P=np.array([np.arange(0.4,0.61,0.01),]).transpose()
n=100000
print P
#[(P,n)]*10

[[ 0.4 ]
 [ 0.41]
 [ 0.42]
 [ 0.43]
 [ 0.44]
 [ 0.45]
 [ 0.46]
 [ 0.47]
 [ 0.48]
 [ 0.49]
 [ 0.5 ]
 [ 0.51]
 [ 0.52]
 [ 0.53]
 [ 0.54]
 [ 0.55]
 [ 0.56]
 [ 0.57]
 [ 0.58]
 [ 0.59]
 [ 0.6 ]]


In [14]:
start=time()
Params=sc.parallelize([(P,n)]*2).repartition(2)
print Params.getNumPartitions()
print time()-start
print Params.take(5)

2
0.0202369689941
[(array([[ 0.4 ],
       [ 0.41],
       [ 0.42],
       [ 0.43],
       [ 0.44],
       [ 0.45],
       [ 0.46],
       [ 0.47],
       [ 0.48],
       [ 0.49],
       [ 0.5 ],
       [ 0.51],
       [ 0.52],
       [ 0.53],
       [ 0.54],
       [ 0.55],
       [ 0.56],
       [ 0.57],
       [ 0.58],
       [ 0.59],
       [ 0.6 ]]), 100000), (array([[ 0.4 ],
       [ 0.41],
       [ 0.42],
       [ 0.43],
       [ 0.44],
       [ 0.45],
       [ 0.46],
       [ 0.47],
       [ 0.48],
       [ 0.49],
       [ 0.5 ],
       [ 0.51],
       [ 0.52],
       [ 0.53],
       [ 0.54],
       [ 0.55],
       [ 0.56],
       [ 0.57],
       [ 0.58],
       [ 0.59],
       [ 0.6 ]]), 100000)]


In [15]:
start=time()
B=Params.map(gen_random).cache()
print B.count()
print 'time=',time()-start

2
time= 0.575860023499


In [18]:
i=0
j=1000
def Count(B):
    return B[:,i:j].sum(axis=1) ##Count the num of `1s` in each row of B matrix
    

In [25]:
j=n/10
start=time()
O=B.map(Count).collect()
print 'time=',time()-start

time= 0.162833929062


In [27]:
print O.shape
O=np.stack(O)
O.shape

(2, 21)


(2, 21)

In [28]:
O ### Should be close to 

array([[4033, 4130, 4215, 4333, 4405, 4544, 4575, 4664, 4792, 4823, 5029,
        5085, 5163, 5268, 5438, 5556, 5582, 5714, 5785, 5895, 6033],
       [3924, 4056, 4158, 4250, 4430, 4510, 4660, 4614, 4865, 4940, 5035,
        5027, 5251, 5300, 5448, 5504, 5547, 5686, 5788, 5875, 5909]])

In [30]:

O>(j/2)

10000


array([[False, False, False, False, False, False, False, False, False,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [False, False, False, False, False, False, False, False, False,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True]], dtype=bool)